// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ykiupyjycxgxwizrjrnc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlraXVweWp5Y3hneHdpenJqcm5jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ2MDU1MzQsImV4cCI6MjA1MDE4MTUzNH0.4lWBStKZWTT4cdLSCeGrG-4888SEWTN1nDHZoIj8zJo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);